// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_for_frondEnd.Models;

public partial class CartItem
{
    public int Id { get; set; }

    public int? Buyer { get; set; }

    public int? PId { get; set; }

    public int? Quantity { get; set; }

    public virtual Member BuyerNavigation { get; set; }

    public virtual Product PIdNavigation { get; set; }
}