// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_for_frondEnd.Models;

public partial class Comment
{
    public int Id { get; set; }

    public int? MId { get; set; }

    public int? EId { get; set; }

    public string Content { get; set; }

    public int? score { get; set; }

    public virtual ICollection<CommentImg> CommentImgs { get; set; } = new List<CommentImg>();

    public virtual Event EIdNavigation { get; set; }

    public virtual Member MIdNavigation { get; set; }
}