// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_for_frondEnd.Models;

public partial class EventPeriod
{
    public int Id { get; set; }

    public int? EId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string Description { get; set; }

    public virtual Event EIdNavigation { get; set; }

    public virtual ICollection<SignUp> SignUps { get; set; } = new List<SignUp>();
}