// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_for_frondEnd.Models;

public partial class Location
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal? Longitude { get; set; }

    public decimal? Latitude { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }

    public string PlusCode { get; set; }

    public int? Capacity { get; set; }

    public virtual ICollection<EventLocation> EventLocations { get; set; } = new List<EventLocation>();

    public virtual ICollection<LocationImg> LocationImgs { get; set; } = new List<LocationImg>();
}