// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_for_frondEnd.Models;

public partial class OrderItem
{
    public int Id { get; set; }

    public int? OId { get; set; }

    public int? PId { get; set; }

    public int? Quantity { get; set; }

    public int? score { get; set; }

    public DateTime? ShippedTime { get; set; }

    public virtual Order OIdNavigation { get; set; }

    public virtual Product PIdNavigation { get; set; }
}