// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_for_frondEnd.Models;

public partial class Order
{
    public int Id { get; set; }

    public int? Buyer { get; set; }

    public int? TotalPrice { get; set; }

    public int? Status { get; set; }

    public DateTime? OrderTime { get; set; }

    public int? DiscountCode { get; set; }

    public virtual Member BuyerNavigation { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual OrderStatus StatusNavigation { get; set; }
}