// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_for_frondEnd.Models;

public partial class SignUp
{
    public int Id { get; set; }

    public int? EpId { get; set; }

    public int? Applicant { get; set; }

    public virtual Member ApplicantNavigation { get; set; }

    public virtual EventPeriod Ep { get; set; }
}